[tool.poetry]
name = "mypkg"
version = "0.1.0"
description = ""
authors = ["ahuigo <1781999+ahuigo@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
#flask = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
